### ISSUE TITLE
Crashes Since Server / API / Client 0.5.4.1

### ISSUE THREAD

**Issue by wofnull** [wows-stats/wows-stats#17]
Hello again, 
I'm in the mid of troubleshooting the problem itself, as far as i can see its a random issue, occuring on random players pulled from the script even in the same battle.

The Output is everytime the same:
Console:

```
E:\Users\wofnu\Desktop\wows-stats>run.bat

E:\Users\wofnu\Desktop\wows-stats>start "" http://localhost:8080

E:\Users\wofnu\Desktop\wows-stats>npm start

> wows-stats@1.2.0 start E:\Users\wofnu\Desktop\wows-stats
> node index.js

wows-stats is running on port: 8080
bigbrotherkamy
Flanker69
Jules_2303
wrobelek1331
Bullyhgw
waldelap
Nodmeister72
yh6yh46h
WoFNuLL
nwpl0710
Rm73
paw76
Aquastic
__Negra__
mircica2014
dakota0857
Jeakz
Hecki
Davituco
a7km
relu_san64
ESPERIENZA
tito_1983
Robbie_Johnston
E:\Users\wofnu\Desktop\wows-stats\index.js:146
                                res.sendStatus(rep.statusCode);
                                                  ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (E:\Users\wofnu\Desktop\wows-stats\index.js:146:23)
    at self.callback (E:\Users\wofnu\Desktop\wows-stats\node_modules\request\request.js:199:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (E:\Users\wofnu\Desktop\wows-stats\node_modules\request\request.js:821:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! wows-stats@1.2.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wows-stats@1.2.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wows-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wows-stats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wows-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Users\wofnu\Desktop\wows-stats\npm-debug.log
```

My first thought was about single users as before with the hidden profiles, but then I saw the error coming up on different players in the same game, depending on when the script was startet, before the player Aquastic pulled the error, after a script restart, the user Robbie_Jonston caused the problem. At the next, another player.

**Comment by tianweiliu** [comment]
@wofnull Thanks for reporting the problem. Very weird. It seems that the node request module somehow returned a null response with error being null. I went ahead and added null check on response. Please checkout the dev branch (https://github.com/tianweiliu/wows-stats/tree/dev) and see if the problem persists.

**Comment by wofnull** [comment]
Works fine, as far as i could test ( 6 Battles without any Crash from the script itself

**Comment by tianweiliu** [comment]
@wofnull thanks for testing! I will go ahead merge master.

**Comment by tianweiliu** [comment]
@wofnull All the changes been pushed to master: https://github.com/wows-stats/wows-stats.
Thanks again for reporting the issue!
